# Site
repository: thiagoandf/thiagoandf.github.io
favicon: images/favicon.ico

darkmode: true

# Personal info
name: Thiago de Andrade Feliciano
title: Full Stack Developer
email: thiagoandf@gmail.com
website: https://thiago.page

# Social links
twitter_username: thiagoandf
github_username: thiagoandf
linkedin_username: thiagoandf

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there! My name is Thiago de Andrade and I'm a Full Stack developer. In this page I'll tell you a little bit about my experience over the years.

  I'm currently working for [QI Tech](https://qitech.com.br), a brazillian financial institution with the goal to bring the "bank-as-a-service" model to Brazil. My role is to maintain and develop the company's platfroms as well as overlook the front-end area of the company.
  
  My whole carreer was based around front-end development, using <mark>React</mark> to bring concepts to life. Recently I started experimenting a bit with back-end development using <mark>Python</mark> and <mark>Node.js</mark>.

  I love being challenged and am extremely attentive to details. I trully believe the moment we stop learning we lose our humanity, so I'm always trying out new things and improving myself.

# Experience Section
# experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Cooking
   - Aviation and Space Exploration
   - Gaming
   - Formula One
   - Science, Futurism, Music, Travelling...

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
